### ISSUE TITLE
Document file handle data format for Linux

### ISSUE THREAD

**Issue by bhourigan** [epam/nfstrace#6]
Hi!

I just discovered nfstrace, a very helpful tool. Sadly I'm stuck with NFSv3 and I'm not understanding how to decode NFS filehandles. I found a tool fhfind[1] but it's for solaris, and doesn't do any special decoding of the inode number. So I started to dig deeper.

I'm using the output from the OFDWS analyzer as my example:

01000601...f28f32b2

I think the string is coming from print_nfs_fh()[2], which does some magic to the opaque data pointer `data' inside the nfs_fh3 structure. Looking deeper I found that data structure is written by xdr_nfs_fh3()[3] up to a maximum size of NFS3_FHSIZE (64).

I turned to nfswatch source[4] and found some detailed decoding in Parse_fh(), but I think it handles a maximum of 32 bytes, while the nfstrace data structure is up to 64.

I turned to the nfsv3 RFC[5] and found some interesting text:

"The file handle contains all the information the server needs to distinguish an individual file. To the client, the file handle is opaque."

My next step is to turn to the Linux kernel source and see if I can figure out how the handle is generated, but given that nfstrace does some special decoding I figured this data structure must be known somewhere. I wanted to reach out in case you can point me in the right direction.

[1] http://heim.ifi.uio.no/kjetilho/hacks/fhfind.perl
[2] https://github.com/epam/nfstrace/blob/master/src/protocols/nfs/nfs_utils.cpp#L68
[3] https://github.com/epam/nfstrace/blob/master/src/protocols/nfs3/nfs3_rpcgen.cpp#L210
[4] http://nfswatch.cvs.sourceforge.net/viewvc/nfswatch/nfswatch/parsenfsfh.c?view=markup
[5] https://www.ietf.org/rfc/rfc1813.txt

**Comment by pkarneliuk** [comment]
Hi Brian,
the filehandle (FH) is just a unique ID of the file on NFS server. It is impossible to "decode" it. In other words, the nfstrace can not expose internals of a NFS server. Because the nfstrace eavesdrops a network traffic.
If you want to see all bytes of FH, so try to run nfstrace with -v 2 option and internal PrintAnalyzer ( -T option). It will print all details of a NFS procedure.

Good news is that you can look at other NFS procedure which is performed for the same FH. For example, you can check LOOKUP procedure. It "assign" FH to filename. Also, you can inspect LOOKUP, CREATE, SYMLINK, MKNOD, LINK, or READDIRPLUS procedure.

OFDWS plugin is deprecated and we will remove it in next release. 
Brian, if you want to have similar functionality I can help you to develop special plugin.  In case of some special details you can write to our email: nfstrace@epam.com

Thank you for feedback and interest to nfstrace!

**Comment by 1llusionary** [comment]
Hi,
Can I decode the file handle on NFS server?
I have read Network File System (NFS) Version 4 Protocol(RFC7530), didn't find the way.If you have any idea,please tell me.
Thank you ! @pkarneliuk
