### ISSUE TITLE
Multiple test failures — nfstrace 0.4

### ISSUE THREAD

**Issue by andrewshadura** [epam/nfstrace#8]
nfstrace 0.4 fails to build from source on almost all Debian architectures, in many cases because of the failing tests.

See:
https://buildd.debian.org/status/fetch.php?pkg=nfstrace&arch=mips&ver=0.4.0-1&stamp=1432512802
https://buildd.debian.org/status/fetch.php?pkg=nfstrace&arch=powerpc&ver=0.4.0-1&stamp=1432506137
https://buildd.debian.org/status/fetch.php?pkg=nfstrace&arch=mipsel&ver=0.4.0-1&stamp=1432517712
https://buildd.debian.org/status/fetch.php?pkg=nfstrace&arch=amd64&ver=0.4.0-1&stamp=1432505949

And others, see: https://buildd.debian.org/status/package.php?p=nfstrace&suite=unstable

**Comment by pkarneliuk** [comment]
Thank you Andrew,
 we will fix these issues.

**Comment by pkarneliuk** [comment]
This change 1d2c62248803091c371095b9cfc5cb048ef43935 fix conversion of CIFS constants on BE arch and fixes 'unit_test_parse' test on MIPS.

**Comment by andrewshadura** [comment]
This turned out to be not enough, some more tests still fail:
https://buildd.debian.org/status/fetch.php?pkg=nfstrace&arch=mips&ver=0.4.0-2&stamp=1434745071

**Comment by andrewshadura** [comment]
And also this: https://buildd.debian.org/status/fetch.php?pkg=nfstrace&arch=s390x&ver=0.4.0-2&stamp=1434729508

And others (except armel, there's a toolchain issue):
https://buildd.debian.org/status/logs.php?pkg=nfstrace&ver=0.4.0-2
-- 
Cheers,
  Andrew

**Comment by pkarneliuk** [comment]
I still work on these issues.

**Comment by pkarneliuk** [comment]
Hi Andrew, I have fixed broken tests on MIPS platform
c11ec8be1c2a6d7ea5ffab71406cedafbe67ec4b:
   1 - functional_stat:eth-ipv4-tcp-smb2-zero-file-rw.pcap.bz2
   2 - functional_drain:eth-ipv4-tcp-smb2-zero-file-rw.pcap.bz2
 16 - functional_stat:eth-ipv4-tcp-smb2-putty.pcap.bz2
 17 - functional_drain:eth-ipv4-tcp-smb2-putty.pcap.bz2
ade6d79ee0c2b9a08bdba0c4f849f61931e24d5e:
  3 - functional_out:eth-ipv4-tcp-smb2-zero-file-rw.pcap.bz2
18 - functional_out:eth-ipv4-tcp-smb2-putty.pcap.bz2
24 - functional_out:eth-ipv4-tcp-nfsv3-4-41-cifs1-2.pcap.bz2
36 - functional_out:eth-ipv4-tcp-cifs2.pcap.bz2
f83ae7b740e2374091bda5b259cf066527a1a2cd:
22 - functional_stat:eth-ipv4-tcp-nfsv3-4-41-cifs1-2.pcap.bz2
23 - functional_drain:eth-ipv4-tcp-nfsv3-4-41-cifs1-2.pcap.bz2
1d2c62248803091c371095b9cfc5cb048ef43935:
59 - unit_test_parse
These changes are tested on [qemu-system-mips vmlinux-3.2.0-4-4kc-malta](https://people.debian.org/~aurel32/qemu/mips) image.
On the [armel](https://buildd.debian.org/status/fetch.php?pkg=nfstrace&arch=armel&ver=0.4.0-2&stamp=1434729008) platform is not supported due to issues with local C++11 toolchain (libstdc++)
On the [sparc](https://buildd.debian.org/status/fetch.php?pkg=nfstrace&arch=sparc&ver=0.4.0-2&stamp=1435002204) platform, functional tests produce strange error messages ("Bus error"). It may be kind of scripting issues.

Anyway, please, rerun build on Debian infrastructure.

**Comment by andrewshadura** [comment]
That helped a lot, thanks. However, basing your tests on floating point
calculations is wrong and leads to unpredictable results:
https://buildd.debian.org/status/fetch.php?pkg=nfstrace&arch=ppc64el&ver=0.4.0-3&stamp=1437680033

**Comment by pkarneliuk** [comment]
Andrew, Thank you a lot. 
I will try to do something with FP and tests

**Comment by pkarneliuk** [comment]
Hello Andrew,

It is me again with nfstrace and some notes regarding to our July discussion at issue #8.
The last build from 23 Jul  reports problems with tests 46 and 47:

46/62 Test #46: functional_stat:eth-ipv4-tcp-nfsv3-4-41-cifs1-2.pcap.bz2 .............***Failed    1.10 sec
--- /«PKGBUILDDIR»/traces/references/breakdown/eth-ipv4-tcp-nfsv3-4-41-cifs1-2.pcap.bz2.ref	2015-04-15 08:21:34.000000000 +0000
+++ /«PKGBUILDDIR»/obj-powerpc64le-linux-gnu/Testing/Temporary/eth-ipv4-tcp-nfsv3-4-41-cifs1-2.pcap.bz2-breakdown.res	2015-07-23 19:33:35.258238475 +0000
@@ -124,7 +124,7 @@
 WRITE_ANDX             Count:  149 ( 67.73%) Min: 0.000 Max: 0.563 Avg: 0.013 StDev: 0.05730764
 NEW_FILE_SIZE          Count:    0 (  0.00%) Min: 0.000 Max: 0.000 Avg: 0.000 StDev: 0.00000000
 CLOSE_AND_TREE_DISC    Count:    0 (  0.00%) Min: 0.000 Max: 0.000 Avg: 0.000 StDev: 0.00000000
-TRANSACTION2           Count:   51 ( 23.18%) Min: 0.000 Max: 0.029 Avg: 0.004 StDev: 0.00614999
+TRANSACTION2           Count:   51 ( 23.18%) Min: 0.001 Max: 0.029 Avg: 0.004 StDev: 0.00614999
 TRANSACTION2_SECONDARY Count:    0 (  0.00%) Min: 0.000 Max: 0.000 Avg: 0.000 StDev: 0.00000000
 FIND_CLOSE2            Count:    0 (  0.00%) Min: 0.000 Max: 0.000 Avg: 0.000 StDev: 0.00000000
 FIND_NOTIFY_CLOSE      Count:    0 (  0.00%) Min: 0.000 Max: 0.000 Avg: 0.000 StDev: 0.00000000
But my commit from Jul 2 replaces the 0.000 with 0.001 in eth-ipv4-tcp-nfsv3-4-41-cifs1-2.pcap.bz2.ref reference file.
So, I am frustrating. It looks like the last build on nfstrace uses old sources.

Could you please rerun build nfstrace on Debian build environment?
I think problems with tests on some arhitectures (armhf mipsel s390x) are already fixed.

**Comment by andrewshadura** [comment]
Could you please tag a release? Cherry-picking patches from git into a patch queue is very error-prone, so better avoid that altogether without a real need.

**Comment by pkarneliuk** [comment]
This is it [release 0.4.1](https://github.com/epam/nfstrace/releases/tag/0.4.1).

**Comment by pkarneliuk** [comment]
https://buildd.debian.org/status/logs.php?pkg=nfstrace&ver=0.4.1-1&suite=sid

tests are passed on all Debian platforms
